# Generated by Django 5.2.2 on 2025-06-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='suppliers',
            field=models.ManyToManyField(to='flowerroom.supplier', verbose_name='Поставщики'),
        ),
        migrations.DeleteModel(
            name='SupplierProduct',
        ),
    ]
