# Generated by Django 5.2.2 on 2025-06-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerroom', '0002_product_suppliers_delete_supplierproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Фотография'),
        ),
    ]
