# Generated by Django 5.2.2 on 2025-06-13 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerroom', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flowerroom.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowerroom.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowerroom.deliveryaddress', verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowerroom.customer', verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowerroom.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowerroom.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowerroom.planttype', verbose_name='Тип растения'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flowerroom.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowerroom.productcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='review',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowerroom.customer', verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowerroom.product', verbose_name='Товар'),
        ),
    ]
