# Generated by Django 5.2.7 on 2025-10-26 16:30

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brandId', models.AutoField(primary_key=True, serialize=False)),
                ('brandName', models.CharField(max_length=100)),
                ('brandDescription', models.TextField()),
                ('brandCountry', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=100)),
                ('categoryDescription', models.TextField()),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('orderStatusId', models.AutoField(primary_key=True, serialize=False)),
                ('orderStatusName', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'orderStatus',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleId', models.AutoField(primary_key=True, serialize=False)),
                ('roleName', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('userId', models.BigAutoField(primary_key=True, serialize=False)),
                ('middleName', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=11)),
                ('birthDate', models.DateField()),
                ('createdAt', models.DateTimeField()),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='core_user_set', related_query_name='core_user', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='core_user_set', related_query_name='core_user', to='auth.permission')),
                ('roleId', models.ForeignKey(db_column='roleId', on_delete=django.db.models.deletion.CASCADE, to='core.role')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'user',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressId', models.BigAutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('house', models.CharField(max_length=50)),
                ('flat', models.CharField(max_length=10, null=True)),
                ('index', models.CharField(max_length=6)),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('auditLogId', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('tableName', models.CharField(max_length=100)),
                ('recordId', models.BigIntegerField()),
                ('oldValues', models.JSONField(null=True)),
                ('newValues', models.JSONField(null=True)),
                ('createdAt', models.DateTimeField()),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auditLog',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.BigAutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deliveryType', models.CharField(max_length=20)),
                ('paymentType', models.CharField(max_length=20)),
                ('paymentStatus', models.CharField(max_length=20)),
                ('note', models.CharField(max_length=100, null=True)),
                ('createdAt', models.DateTimeField()),
                ('addressId', models.ForeignKey(db_column='addressId', on_delete=django.db.models.deletion.CASCADE, to='core.address')),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('orderStatusId', models.ForeignKey(db_column='orderStatusId', on_delete=django.db.models.deletion.CASCADE, to='core.orderstatus')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='ParentChild',
            fields=[
                ('parentChildId', models.BigAutoField(primary_key=True, serialize=False)),
                ('childId', models.ForeignKey(db_column='childId', on_delete=django.db.models.deletion.CASCADE, related_name='child_relations', to=settings.AUTH_USER_MODEL)),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='parent_relations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parentChild',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.BigAutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=100)),
                ('productDescription', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ageRating', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('weightKg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dimensions', models.CharField(max_length=50)),
                ('brandId', models.ForeignKey(db_column='brandId', on_delete=django.db.models.deletion.CASCADE, to='core.brand')),
                ('categoryId', models.ForeignKey(db_column='categoryId', on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orderId', models.ForeignKey(db_column='orderId', on_delete=django.db.models.deletion.CASCADE, to='core.order')),
                ('productId', models.ForeignKey(db_column='productId', on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'db_table': 'orderItem',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartId', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('productId', models.ForeignKey(db_column='productId', on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('productAttributeId', models.BigAutoField(primary_key=True, serialize=False)),
                ('productAttributeName', models.CharField(max_length=100)),
                ('productAttributeValue', models.CharField(max_length=100)),
                ('productAttributeUnit', models.CharField(max_length=50, null=True)),
                ('productId', models.ForeignKey(db_column='productId', on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'db_table': 'productAttribute',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('productImageId', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=500)),
                ('altText', models.CharField(max_length=100)),
                ('isMain', models.BooleanField()),
                ('productId', models.ForeignKey(db_column='productId', on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'db_table': 'productImage',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewId', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('reviewText', models.TextField(null=True)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('productId', models.ForeignKey(db_column='productId', on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wishlistId', models.BigAutoField(primary_key=True, serialize=False)),
                ('productId', models.ForeignKey(db_column='productId', on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wishlist',
            },
        ),
    ]
