# Generated by Django 5.2.7 on 2025-10-26 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'verbose_name': 'Журнал аудита', 'verbose_name_plural': 'Журналы аудита'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Позиция заказа', 'verbose_name_plural': 'Позиции заказов'},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name': 'Статус заказа', 'verbose_name_plural': 'Статусы заказов'},
        ),
        migrations.AlterModelOptions(
            name='parentchild',
            options={'verbose_name': 'Родитель-ребенок', 'verbose_name_plural': 'Родитель-ребенок связи'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name': 'Атрибут продукта', 'verbose_name_plural': 'Атрибуты продуктов'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Изображение продукта', 'verbose_name_plural': 'Изображения продуктов'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'Список желаний', 'verbose_name_plural': 'Списки желаний'},
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='address',
            name='flat',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='address',
            name='house',
            field=models.CharField(max_length=50, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='address',
            name='index',
            field=models.CharField(max_length=6, verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=100, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='address',
            name='userId',
            field=models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to='core.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=100, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='createdAt',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='newValues',
            field=models.JSONField(blank=True, null=True, verbose_name='Новые значения'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='oldValues',
            field=models.JSONField(blank=True, null=True, verbose_name='Старые значения'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='recordId',
            field=models.BigIntegerField(verbose_name='ID записи'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='tableName',
            field=models.CharField(max_length=100, verbose_name='Имя таблицы'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='userId',
            field=models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to='core.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brandCountry',
            field=models.CharField(max_length=100, verbose_name='Страна бренда'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brandDescription',
            field=models.TextField(verbose_name='Описание бренда'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brandName',
            field=models.CharField(max_length=100, verbose_name='Название бренда'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='productId',
            field=models.ForeignKey(db_column='productId', on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='userId',
            field=models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to='core.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='category',
            name='categoryDescription',
            field=models.TextField(verbose_name='Описание категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='categoryName',
            field=models.CharField(max_length=100, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='order',
            name='addressId',
            field=models.ForeignKey(db_column='addressId', on_delete=django.db.models.deletion.CASCADE, to='core.address', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='createdAt',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveryType',
            field=models.CharField(max_length=20, verbose_name='Тип доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderStatusId',
            field=models.ForeignKey(db_column='orderStatusId', on_delete=django.db.models.deletion.CASCADE, to='core.orderstatus', verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentStatus',
            field=models.CharField(max_length=20, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentType',
            field=models.CharField(max_length=20, verbose_name='Тип оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итого'),
        ),
        migrations.AlterField(
            model_name='order',
            name='userId',
            field=models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to='core.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='orderId',
            field=models.ForeignKey(db_column='orderId', on_delete=django.db.models.deletion.CASCADE, to='core.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='productId',
            field=models.ForeignKey(db_column='productId', on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unitPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='orderStatusName',
            field=models.CharField(max_length=100, verbose_name='Название статуса заказа'),
        ),
        migrations.AlterField(
            model_name='parentchild',
            name='childId',
            field=models.ForeignKey(db_column='childId', on_delete=django.db.models.deletion.CASCADE, related_name='child_relations', to='core.user', verbose_name='Ребенок'),
        ),
        migrations.AlterField(
            model_name='parentchild',
            name='userId',
            field=models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='parent_relations', to='core.user', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ageRating',
            field=models.IntegerField(verbose_name='Возрастной рейтинг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brandId',
            field=models.ForeignKey(db_column='brandId', on_delete=django.db.models.deletion.CASCADE, to='core.brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categoryId',
            field=models.ForeignKey(db_column='categoryId', on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimensions',
            field=models.CharField(max_length=50, verbose_name='Размеры'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productDescription',
            field=models.TextField(verbose_name='Описание продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productName',
            field=models.CharField(max_length=100, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weightKg',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес (кг)'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='productAttributeName',
            field=models.CharField(max_length=100, verbose_name='Название атрибута'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='productAttributeUnit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='productAttributeValue',
            field=models.CharField(max_length=100, verbose_name='Значение атрибута'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='productId',
            field=models.ForeignKey(db_column='productId', on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='altText',
            field=models.CharField(max_length=100, verbose_name='Альтернативный текст'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='isMain',
            field=models.BooleanField(default=False, verbose_name='Основное изображение'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='productId',
            field=models.ForeignKey(db_column='productId', on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='url',
            field=models.CharField(max_length=500, verbose_name='URL изображения'),
        ),
        migrations.AlterField(
            model_name='review',
            name='createdAt',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='productId',
            field=models.ForeignKey(db_column='productId', on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewText',
            field=models.TextField(blank=True, null=True, verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='review',
            name='updatedAt',
            field=models.DateTimeField(verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='review',
            name='userId',
            field=models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to='core.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthDate',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='createdAt',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstName',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastName',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middleName',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roleId',
            field=models.ForeignKey(db_column='roleId', on_delete=django.db.models.deletion.CASCADE, to='core.role', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='productId',
            field=models.ForeignKey(db_column='productId', on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='userId',
            field=models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to='core.user', verbose_name='Пользователь'),
        ),
    ]
