# Generated by Django 5.2.7 on 2025-10-27 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_address_options_alter_auditlog_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='id',
            new_name='orderItemId',
        ),
    ]
