# Generated by Django 5.2.7 on 2025-10-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_id_orderitem_orderitemid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliveryType',
            field=models.CharField(choices=[('самовывоз', 'Самовывоз'), ('пункт выдачи', 'Пункт выдачи'), ('курьером', 'Курьером')], max_length=20, verbose_name='Тип доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentStatus',
            field=models.CharField(choices=[('ждет оплаты', 'Ждет оплаты'), ('оплачено', 'Оплачено'), ('возврат средств', 'Возврат средств'), ('средства возвращены', 'Средства возвращены')], max_length=30, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentType',
            field=models.CharField(choices=[('онлайн', 'Онлайн'), ('картой при получении', 'Картой при получении'), ('наличными при получении', 'Наличными при получении')], max_length=30, verbose_name='Тип оплаты'),
        ),
    ]
