# Generated by Django 5.2.7 on 2025-11-15 20:00

from django.db import migrations

def add_default_roles(apps, schema_editor):
    Role = apps.get_model('core', 'Role')
    
    # Try to get or create roles, handling existing ones
    try:
        Role.objects.get_or_create(roleId=1, defaults={'roleName': 'Покупатель'})
        Role.objects.get_or_create(roleId=2, defaults={'roleName': 'Ребенок'})
        Role.objects.get_or_create(roleId=3, defaults={'roleName': 'Менеджер'})
        Role.objects.get_or_create(roleId=4, defaults={'roleName': 'Администратор'})
    except Exception:
        # If there's any issue, just create them without specific IDs
        if not Role.objects.filter(roleName='Покупатель').exists():
            Role.objects.create(roleName='Покупатель')
        if not Role.objects.filter(roleName='Ребенок').exists():
            Role.objects.create(roleName='Ребенок')
        if not Role.objects.filter(roleName='Менеджер').exists():
            Role.objects.create(roleName='Менеджер')
        if not Role.objects.filter(roleName='Администратор').exists():
            Role.objects.create(roleName='Администратор')

def reverse_default_roles(apps, schema_editor):
    Role = apps.get_model('core', 'Role')
    Role.objects.filter(roleName__in=['Покупатель', 'Ребенок', 'Менеджер', 'Администратор']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_order_deliverytype_alter_order_paymentstatus_and_more'),
    ]

    operations = [
        migrations.RunPython(add_default_roles, reverse_default_roles),
    ]