# Generated by Django 5.2.7 on 2025-11-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_default_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='roleName',
            field=models.CharField(max_length=100, verbose_name='Название роли'),
        ),
    ]
