name: Django check

on:
  push:
    branches: [ pipeline ]

  # pull_request:

jobs:
  build: # Проверка сборки проекта
    name: Build Django project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with: 
          python-version: '3.13'

      - name: Create venv and install
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Check Django build
        run: |
          source .venv/bin/activate
          echo "Проверка сборки проекта"
          python manage.py check
          python manage.py makemigrations --check --dry-run
          python manage.py collectstatic --noinput --dry-run
          echo "Проект успешно собран"

  linter: # Проверка синтаксических ошибок линтером
    name: Check Django project with flake8
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with: 
          python-version: '3.13'

      - name: Create venv and install
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check errors with flake8
        run: |
          source .venv/bin/activate
          echo "Проверка синтаксических ошибок с помощью flake8"
          pip install flake8
          python -m flake8 joybox
          echo "Проверка синтаксических ошибок завершена"
        continue-on-error: true

  check: # 2 дополнительные задачи
    name: Check Django project safety and dependencies
    runs-on: ubuntu-latest
    needs: linter
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with: 
          python-version: '3.13'

      - name: Create venv and install
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check project safety with bandit
        run: |
          source .venv/bin/activate
          echo "Проверка безопасности"
          pip install bandit
          bandit -r .
          echo "Проверка безопасности пройдена успешно"
        continue-on-error: true
        
      - name: Check project dependencies
        run: | 
          source .venv/bin/activate
          echo "Проверка зависимостей на актуальность"
          pip list --outdated
          pip check
          echo "Проверка зависимостей на актуальность пройдена успешно"        
